apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat-app
  name: chat-service
  namespace: default
spec:
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: chat-app
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chat-app-deployment
  labels:
    app: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
        - name: chat-app
          image: gcr.io/ic-cloud-native/web-chat:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001